name: Stale Branches

on:
  schedule:
    - cron: '0 6 * * 1-5'
      workflow_dispatch:


permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v5.0.0
