name: stale repo identifier

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write



    steps:
      - uses: actions/checkout@v4

      - name: Run stale_repos tool
        uses: github/stale-repos@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXEMPT_TOPICS: "keep,template"
          INACTIVE_DAYS: 365
          ACTIVITY_METHOD: "pushed"
          ADDITIONAL_METRICS: "release,pr"


