name: stale-branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'
      


permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v8.1.1
        with:
          days-before-stale: 120
          dry-run: true
          
